version: '3.8'  # Specify a version for better compatibility
services:
  db:
    image: mysql:8.0
    container_name: mysql_container_web
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasksul
      MYSQL_ROOT_HOST: '%'  # Allow root to connect from any host
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # Add health check to ensure MySQL is ready
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: appweb
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Wait for MySQL to be healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tasksul
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

volumes:
  mysql_data: